"""
Defining constants for the project.
"""


ICON_UPDATE = "mdi:update"
DOMAIN = "cz_air_quality"
CONF_STOP_SEL = "station_selector"
STATION_LIST = [
    "Praha 8-Karlín",
    "Praha 2-Legerova (hot spot)",
    "Praha 1-n. Republiky",
    "Praha 2-Riegrovy sady",
    "Praha 10-Vršovice",
    "Praha 9-Vysočany",
    "Okraj Prahy",
    "Praha 6-Břevnov",
    "Praha 4-Chodov",
    "Praha 8-Kobylisy",
    "Letiště Praha",
    "Praha 4-Libuš",
    "Praha 10-Průmyslová",
    "Praha 10-Šrobárova",
    "Praha 5-Stodůlky",
    "Praha 6-Suchdol",
    "Praha 7-Holešovice",
    "Beroun",
    "Kutná Hora-Orebitská",
    "Kladno-střed města",
    "Kladno-Švermov",
    "Kolín SAZ",
    "Kralupy nad Vltavou-sportoviště",
    "Mladá Boleslav",
    "Ondřejov",
    "Příbram-Březové Hory",
    "Rožďalovice-Ruská",
    "Tobolka-Čertovy schody",
    "České Budějovice",
    "Čes. Budějovice-Třešň.",
    "Churáňov",
    "Kocelovice",
    "Prachatice",
    "Strakonice-ZŠ Strakonice",
    "Tábor",
    "Hojná Voda",
    "Klatovy soud",
    "Kamenný Újezd",
    "Plzeň-Slovany",
    "Plzeň-střed",
    "Plzeň-Lochotín",
    "Plzeň-Doubravka",
    "Plzeň - mobil",
    "Přimda",
    "Cheb",
    "Přebuz",
    "Sokolov",
    "Děčín",
    "Doksany",
    "Chomutov",
    "Krupka",
    "Lom",
    "Litoměřice",
    "Měděnec",
    "Most",
    "Rudolice v Horách",
    "Sněžník",
    "Štětí",
    "Teplice ",
    "Tušimice",
    "Ústí n. L.-Prokopa Diviše",
    "Ústí n.L.-Všebořická (hot spot)",
    "Ústí n.L.-Kočkov",
    "Ústí n.L.-město",
    "Česká Lípa",
    "Frýdlant",
    "Horní Vítkov",
    "Liberec-Rochlice",
    "Souš",
    "Uhelná",
    "Hradec Králové-Brněnská",
    "Hradec Králové-observatoř",
    "Hr.Král.-Sukovy sady",
    "Krkonoše-Rýchory",
    "Polom",
    "Trutnov - Tkalcovská",
    "Moravská Třebová - Piaristická.",
    "Pardubice-Rosice",
    "Pardubice Dukla",
    "Svratouch",
    "Jihlava-Znojemská",
    "Kostelní Myslová",
    "Košetice",
    "Pelhřimov",
    "Třebíč",
    "Žďár nad Sázavou",
    "Bílý Kříž",
    "Červená hora",
    "Český Těšín",
    "Frýdek-Místek",
    "Havířov ZÚ",
    "Havířov",
    "Karviná ZÚ",
    "Karviná",
    "Malá Morávka",
    "Nošovice",
    "Ostrava-Českobratrská (hot spot)",
    "Ostrava-Fifejdy",
    "Ostrava-Hrušov",
    "Ostrava-Mariánské Hory",
    "Ostrava-Poruba DD",
    "Ostrava-Poruba ČHMÚ",
    "Ostrava-Přívoz",
    "Ostrava-Radvanice ZÚ",
    "Ostrava-Radvanice OZO",
    "Opava-Kateřinky",
    "Ostrava-Zábřeh",
    "Rychvald",
    "Studénka",
    "Třinec-Kanada",
    "Třinec-Kosmos",
    "Věřňovice-Dolní Lutyně",
    "Vrbno pod Pradědem",
    "Zátor"
    ]


